pipeline {
     agent {
       docker { image 'polaris-slave03:v4.2' }
     }
     stages {
       stage('clone') {
         steps {
             //cleanWs()
             //sh'python3 --version'
            sh 'rm -rf kodiak'
             sh 'ssh-keyscan -H github.com >> /home/jenkins/.ssh/known_hosts'
         sh 'git clone git@github.com:Trail-Tech/kodiak.git'
        }
       }

       stage('build') {
         steps {

            sh 'ls -ltr'
            //sh 'mkdir work;cd work;mkdir downloads'
            sh 'cd kodiak;ls -al'
            //sh 'chmod 777 /home/jenkins/kodiakbuild.sh'
           // sh 'cd /home/jenkins;bash kodiakbuild.sh'

        }
       }
       stage('Approval') {
            steps {
                script {
                    input id: 'Merge', message: 'Ready to merge?', submitter: 'admin' 

                }
            }
        }
       stage ('Invoke_Merge_job') {
            steps {
                build job: 'auto-merge', parameters: [
                string(name: 'Source_Branch', value: "Development")
                ]
                 script {
                    
		    env.commiter_id = sh(script:'git log --since=6.hours --pretty=format:%an', returnStdout: true).trim()
                  
  
			 echo "${commiter_id}"
                    
                    env.commiter_mail = sh(script:  'echo $commiter_id | python3 /var/lib/jenkins/workspace/$JOB_NAME/commitmail.py', returnStdout: true)
			 echo "${commiter_mail}"
                
                }
            }
        }
    }
	
    post{
        always{
             mail to:"{env.commiter_mail}",
            subject: "build-Status: $JOB_NAME",
            body: "JOB-LINK to check-- http://100.20.0.129:8080/job/$JOB_NAME/$BUILD_NUMBER"
        }
    }
        }
